### ISSUE TITLE
Add per word timing support

### ISSUE THREAD

**Issue by itaibh** [mcanam/liricle#1]
The LRC file format also specifies per word timing, in the format of:

```
[01:06] <01:07>first <01:09>middle <01:20>last <01:25>
```
Which means the line starts at 1:06, the first word is marked at 01:07, the second word at 01:09, the last at 01:20. If animated then the first word will take 2 seconds to fill, the second will take 11 and the last will take 5 seconds to fill until the next line time arrives.

**Comment by mcanam** [comment]
Hi @itaibh :wave: I think enhanced lrc is less commonly used, I don't know. I'm having a hard time finding a fairly complete source about this variant. but it doesn't matter there must be another way to find a solution :sweat_smile: or if you have an enhanced lrc sample file it will be very helpful. 

Thank you very much :raised_hands:

**Comment by itaibh** [comment]
From https://en.wikipedia.org/wiki/LRC_%28file_format%29?wprov=sfla1

```
[ar: Jefferson Airplane]
[al: Surrealistic Pillow]
[au: Jefferson Airplane]
[length: 2:58]
[by: lrc-maker]
[ti: Somebody to Love]

[00:00.00] <00:00.04> When <00:00.16> the <00:00.82> truth <00:01.29> is <00:01.63> found <00:03.09> to <00:03.37> be <00:05.92> lies 
[00:06.47] <00:07.67> And <00:07.94> all <00:08.36> the <00:08.63> joy <00:10.28> within <00:10.53> you <00:13.09> dies 
[00:13.34] <00:14.32> Don't <00:14.73> you <00:15.14> want <00:15.57> somebody <00:16.09> to <00:16.46> love
```

**Comment by mcanam** [comment]
dam, i didn't notice 😅. thank you very much 🤣

**Comment by mcanam** [comment]
would you also like to contribute with code? feel free to fork this repo

**Comment by itaibh** [comment]
how do you test your code?

**Comment by itaibh** [comment]
I had an idea replacing TIME_REGEX with this format:

```
const TIME_REGEX = /\[\d{2}:\d{2}(.\d{2,})?\]{1,}.*?((<\d{2}:\d{2}(.\d{2,})?>)(.*?))*/g;
```

so adding further detection groups for timed words, but I can't test it.

**Comment by mcanam** [comment]
> how do you test your code?

for now i testing it using native module by modify the script tag in the `index.html` file.
to check the regex i use an online tool like https://regexr.com/ to see the result instantly.

I know this is terrible and I hope you or someone else can make it better :smile:

**Comment by mcanam** [comment]
> I had an idea replacing TIME_REGEX with this format:
> 
> ```
> const TIME_REGEX = /\[\d{2}:\d{2}(.\d{2,})?\]{1,}.*?((<\d{2}:\d{2}(.\d{2,})?>)(.*?))*/g;
> ```
> 
> so adding further detection groups for timed words, but I can't test it.

we can give it a try, but i've made some changes maybe you should review it
https://github.com/mcanam/liricle/tree/per-word-timing-support

**Comment by mcanam** [comment]
parser output:
![Screenshot_20220714_042053](https://user-images.githubusercontent.com/67553080/178847677-0c620ba4-4495-4af1-a993-ed41036f370d.png)

we still get normal text and line times. so we can sync those two variants together.

I just want to make this library able to handle all lrc variants without any additional configuration :laughing:

**Comment by itaibh** [comment]
looks great, but since I forked `main` I don't get this branch. Can you merge to `main`?

**Comment by mcanam** [comment]
> looks great, but since I forked `main` I don't get this branch. Can you merge to `main`?

try to run `git fetch` to get new branch

**Comment by itaibh** [comment]
I actually copied from your branch and completed implementation of a full karaoke interface upon it, still buggy and the code could be improved massively.

**Comment by mcanam** [comment]
> I actually copied from your branch and completed implementation of a full karaoke interface upon it, still buggy and the code could be improved massively.


yeah because this feature is still in development branch so it can't be used for real implementation yet. if this feature is ready and stable we will merge it with main branch and release new version :raised_hands:

**Comment by mcanam** [comment]
and I think we also need to improve the documentation on how to use it :laughing:

**Comment by itaibh** [comment]
https://github.com/mcanam/liricle/pull/2/

**Comment by mcanam** [comment]
almost done, please check the latest commit :tada:

**Comment by mcanam** [comment]
v3.0.0 has been released :tada:
